[package]
authors = ["Kenan Sulayman <kenan@sly.mn>"]
name = "6EQUJ5"
version = "0.1.0"

[dependencies]
hyper = "0.9.10"
json = "0.10.2"
regex = "0.2.1"
telegram-bot = "0.4.2"
url = "1.2.4"

[profile]

[profile.dev]
codegen-units = 1
debug = true
debug-assertions = true
lto = false
opt-level = 0
panic = "unwind"
rpath = false

[profile.release]
debug = false
debug-assertions = false
lto = true
opt-level = 3
panic = "abort"
rpath = false
